### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Leng-bingo** [appleloveme/dg_gpu_queuer#1]
程序是不是不完整呀，运行不起来

**Comment by Leng-bingo** [comment]
queuer文件报错

**Comment by deng1fan** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    方便贴下报错信息吗
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年05月7日 14:23
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Mute-ZEN/GpuQueuer] 运行报错 (Issue #1)
        
      
    
  
  
queuer文件报错

**Comment by Leng-bingo** [comment]
log没有，Device也没有

**Comment by Leng-bingo** [comment]
文件一打开就是红的，有些变量都是不全的

**Comment by Leng-bingo** [comment]
你git一下现在的仓库，是运行不起来的

**Comment by deng1fan** [comment]
仓库已更新，我在本地可以运行，多谢提醒！

**Comment by Leng-bingo** [comment]
我试一下，这个能达到什么效果我有点没理解，我们有一个四张卡的服务器，想做成申请后学生们使用。请问是这样么

**Comment by deng1fan** [comment]
“申请后学生们使用”这句话没太理解具体是什么意思

**Comment by Leng-bingo** [comment]
就是四张卡，比如一个人提交了申请，那么这张卡就分配给他了，别人就不会用了

**Comment by deng1fan** [comment]
可以的

**Comment by Leng-bingo** [comment]
好的，我研究一下，非常感谢您的回复

**Comment by Leng-bingo** [comment]
运行queuer文件，显示

成功登记Gpu使用信息到Redis服务器！
自动选择GPU：[2]

同时maintain文件显示，发现 GPU占用信息 中存在残余数据，已清除，进程为3319705。

**Comment by deng1fan** [comment]
这应该是成功的

**Comment by Leng-bingo** [comment]
那这我申请成功后，redis数据库中没有这条信息被删除了，我怎样确认呢。

**Comment by deng1fan** [comment]
可以试试将主函数设置成下面这样
```
if __name__ == '__main__':
    config = Config()
    config = set_config_gpus(config)
    sys.sleep(60*10)
    print()
```

**Comment by Leng-bingo** [comment]
现在我可以无限制的排队，每一次都是成功的

**Comment by Leng-bingo** [comment]
> 可以试试将主函数设置成下面这样
> 
> ```
> if __name__ == '__main__':
>     config = Config()
>     config = set_config_gpus(config)
>     sys.sleep(60*10)
>     print()
> ```

我试一下

**Comment by deng1fan** [comment]
因为程序运行之后就退出了，然后被维护程序清除了记录，所以可以一直运行

**Comment by Leng-bingo** [comment]
sys.sleep
是要引入什么包呢

**Comment by deng1fan** [comment]
import sys

**Comment by Leng-bingo** [comment]
sys也没有sleep的用法呀，是不是time.sleep呀

**Comment by deng1fan** [comment]
奥对，是 time 😂，我总记不清这两个

**Comment by Leng-bingo** [comment]
我还去百度了半天，哈哈

**Comment by deng1fan** [comment]
意会意会 😂

**Comment by Leng-bingo** [comment]
我这样获取到了gpu，然后自己再去使用对应的gpu？

**Comment by Leng-bingo** [comment]
主要还是靠自觉是么

**Comment by deng1fan** [comment]
您是想实现那种申请-审批的效果吗

**Comment by Leng-bingo** [comment]
是的

**Comment by Leng-bingo** [comment]
通过分配用户名密码和显卡，不审批通过无法使用，有这种可以借鉴的项目么

**Comment by deng1fan** [comment]
想要用户名和显卡之间的对应关系是可变（每次动态申请审批）的还是不可变（写死）的呢

**Comment by Leng-bingo** [comment]
不用写死，哪张卡有位置就分配哪张卡就可以。分配完之后，别人就不会再分配此卡，直到该用户释放卡的资源

**Comment by deng1fan** [comment]
那您可以试试修改一下这个排队程序就可以实现，redis 很适合做这种任务，其他的项目我了解到的好像并没有这种功能

**Comment by Leng-bingo** [comment]
好的，非常感谢，麻烦了~

**Comment by deng1fan** [comment]
不客气
